# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  #config.vm.provision "shell", path: "bootstrap.sh"

  # Master Server
  config.vm.define "openstack" do |openstack|
    openstack.vm.box = "centos/7"
    openstack.disksize.size = '70GB'
    openstack.vm.hostname = "openstack.example.com"
    openstack.vm.network "private_network", ip: "172.31.0.110"
    openstack.vm.provider "virtualbox" do |v|
      v.name = "openstack"
      v.memory = 16048
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
  end
end
